openapi: 3.0.0
info:
  version: '1.0'
  title: '... API'
  description: 'Lab003 PAB'
servers:
  - url: 'http://localhost:8080'
paths:
  /test:
    get:
      responses:
        '200':
          description: successful operation
  /test/{id}:
    get:
      responses:
        '200':
          description: successful operation
        '400':
          description: unsuccessful operation
    parameters:
      - $ref: '#/components/parameters/id'      
components:
  parameters:
    id:
      name: id
      in: path
      description: ID of ...
      required: true
      schema:
        type: integer
  schemas:
    SampleSchema:
      type: object
      required:
        - title
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
          minLength: 2
          maxLength: 50
      example:
        id: 1
        title: ...