openapi: 3.0.0
info:
  version: '1.0'
  title: 'Countries API Laravel'
  description: 'Lab003 PAB'
servers:
  - description: 'Laravel'
    url: 'http://localhost:8000/api'
paths:
  /countries:
    get:
      responses:
        "200":
          description: succesfull operation
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/CountryCollection"
      tags:
        - countries
      summary: Returns all countries
    post:
      requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoreCountryRequest'
          description: Inventory item to add
      responses:
        "201":
          description: country created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Country"
        "422":
          description: "invalid input, object invalid"
      tags:
        - countries
      summary: Create new country
  /countries/{countryId}:
    get:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/CountryResource"
        '404':
          description: not found
      parameters:
        - $ref: '#/components/parameters/countryId'
      tags:
        - countries
      summary: Get specified country
    put:
      requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCountryRequest'
          description: New values
      responses:
        "200":
          description: country updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Country"
        "422":
          description: "invalid input, object invalid"
        '404':
          description: not found
      parameters:
        - $ref: '#/components/parameters/countryId'
      tags:
        - countries
      summary: Update country
    delete:
      parameters:
        - $ref: '#/components/parameters/countryId'
      tags:
        - countries
      summary: Delete selected country
      responses:
        '204':
          description: no content
        '404':
          description: not found
components:
  parameters:
    countryId:
      name: countryId
      in: path
      description: ID of country to use
      required: true
      schema:
        type: integer
  schemas:
    Country:
      type: object
      required:
        - id
        - name
        - code
        - currency
        - area
        - language
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: Name
          maxLength: 50
        code: 
          type: string
          maxLength: 3
          example: COD
        currency:
          type: string
          minLength: 2
          example: PLN
        area:
          type: integer
          minimum: 0
          example: 100000
        language:
          type: string
          maxLength: 50
          example: language
    CountryResource:
      type: object
      required:
        - name
        - code
        - currency
        - area
        - language
      properties:
        name:
          type: string
          example: Name
          maxLength: 50
        code: 
          type: string
          maxLength: 3
          example: COD
        currency:
          type: string
          minLength: 2
          example: PLN
        area:
          type: integer
          minimum: 0
          example: 100000
        language:
          type: string
          maxLength: 50
          example: language
    CountryCollection:
      type: array
      items:
        $ref: "#/components/schemas/CountryResource"
    StoreCountryRequest:
      $ref: "#/components/schemas/CountryResource"
    UpdateCountryRequest:
      type: object
      properties:
        name:
          type: string
          example: Name
          maxLength: 50
        code: 
          type: string
          maxLength: 3
          example: COD
        currency:
          type: string
          minLength: 2
          example: PLN
        area:
          type: integer
          minimum: 0
          example: 100000
        language:
          type: string
          maxLength: 50
          example: language