openapi: 3.0.0
info:
  version: '1.0'
  title: 'Countries API Laravel & JWT Auth'
  description: Lab006 PAB
servers:
  - description: Laravel
    url: http://localhost:8000/api
paths:
  /auth/login:
    post:
      tags:
        - auth 
      summary: Get a JWT via given credentials
      responses:  
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_token'                  
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credentials' 
  /countries:
    get:
      tags:
        - countries
      summary: Returns all countries
      responses:
        '200':
          description: A list of countries.
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CountryCollection'
    post:
      tags:
        - countries
      summary: Store a new country
      operationId: storeCountry
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryResource'
        '422':
          description: unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreCountryRequest'
        description: new coutry data
        required: true              
  /countries/{countryId}:
    get:
      tags:
        - countries
      description: Returns a country based on ID
      summary: Find country by ID
      responses:
        '200':
          description: country response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryResource'
        '404':
          description: 'not found'
    put:
      tags:
        - countries
      summary: Update a country
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryResource'
        '404':
          description: country not found
        '422':
          description: unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCountryRequest'
        description: updated country data
        required: true 
    delete:
      tags:
        - countries
      summary: Delete a country
      responses:
        '204':
          description: successful operation
        '404':
          description: not found
    parameters:
      - $ref: '#/components/parameters/countryId'
components:
  parameters:
    countryId:
      name: countryId
      in: path
      description: ID of country to use
      required: true
      schema:
        type: integer
  schemas:
    Country:
      type: object
      required:
        - name
        - code
        - currency
        - area
        - language
      properties:
        name:
          type: string
          maxLength: 50
          example: Name
        code:
          type: string
          maxLength: 3
          example: COD
        currency:
          type: string
          maxLength: 30
          example: Currency          
        area:
          type: integer
          format: int32
          minimum: 0
          example: 100000
        language:
          type: string
          maxLength: 50
          example: language
    CountryResource:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
      allOf:
        - $ref: '#/components/schemas/Country'
        - type: object
    CountryCollection:
      type: object  
      properties:
        data:
          type: array
          items:
           $ref: '#/components/schemas/CountryResource'
    StoreCountryRequest:
      type: object 
      allOf:
        - $ref: '#/components/schemas/Country'
        - type: object
    UpdateCountryRequest:
      type: object 
      allOf:
        - $ref: '#/components/schemas/Country'
        - type: object
    credentials:  
      type: object
      required:
      - email
      - password
      properties:
        email:
          type: string  
          format: email
          example: user@email.com
        password:
          type: string 
          example: pass
    access_token:
      type: object
      properties:
        access_token:
          type: string     
          example: header.payload.signature
        token_type:
          type: string 
          example: bearer            
        expires_in:
          type: integer 
          example: 60          
